<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<div class="header-srvc-page"><p>SERVICES</p>
<div class="header-bottom">&nbsp;</div>
</div>

<div class="dv-srvc-page">
	<div class="div-services-page">
		<ul class="ul-services-page">
			<li class="li-services-page">
				<p class="service-icon"><img src="<?php echo $mediaUrl?>wysiwyg/Insurance-icon.png" /></p>
				<p class="lbl-service">Insurance</p>
				<p class="service-desc">
					Do you, sometimes, ever find yourself in the middle of an agony that, anytime, unforeseen events happen when you drive. If you do, then you are drive-conscious and if you are, then here’s our answer to your question.
				</p>
				<p class="services-redirect"><a class="services-redirect" href="insurance">KNOW MORE</a></p>
			</li>
			
			<li class="li-services-page">
				<p class="service-icon"><img src="<?php echo $mediaUrl?>wysiwyg/Car_Maintenance-icon.png" /></p>
				<p class="lbl-service">Car Maintenance</p>
				<p class="service-desc">
					Your car deserves the best car maintenance. Keep your car running fresh and free from unexpected breakdowns.
				</p>
				<p class="services-redirect"><a class="services-redirect" href="car-maintenance">KNOW MORE</a></p>
			</li>
			
			<li class="li-services-page">
				<p class="service-icon"><img src="<?php echo $mediaUrl?>wysiwyg/Parts_Installation-icon.png" /></p>
				<p class="lbl-service">Parts Installation</p>
				<p class="service-desc">
					We have highly trained mechanics who can go straight to you to supervise and run the installation of the auto parts that you want for your car anywhere in the country.
				</p>
				<p class="services-redirect"><a class="services-redirect" href="parts-installation">KNOW MORE</a></p>
			</li>

		</ul>
		
		<ul class="ul-services-page">	

			<li class="li-services-page">
				<p class="service-icon"><img src="<?php echo $mediaUrl?>wysiwyg/Rentals_and_Leasing-icon.png" /></p>
				<p class="lbl-service">Rentals and Leasing</p>
				<p class="service-desc">
					We also offer car rentals and leasing that assures the overall safety and security of the clients
				</p>
				<p class="services-redirect"><a class="services-redirect" href="car-rentals.html">KNOW MORE</a></p>
			</li>

			<li class="li-services-page">
				<p class="service-icon"><img src="<?php echo $mediaUrl?>wysiwyg/Parts_Finder-icon.png" /></p>
				<p class="lbl-service">Parts Finder</p>
				<p class="service-desc">
					Locate an auto part that you need in just seconds at autosupply.ph
					While we recommend and suggest other related choices that are possibly useful and you may want for your car. 
				</p>
				<p class="services-redirect"><a class="services-redirect" href="parts-finder">KNOW MORE</a></p>
			</li>
			
			<li class="li-services-page">
				<p class="service-icon"><img src="<?php echo $mediaUrl?>wysiwyg/Car_Finder-icon.png" /></p>
				<p class="lbl-service">Cars Finder</p>
				<p class="service-desc">
					Find a car that fits your preference on the spot.
					From oldies and pre-owned cars to the latest brand-new models.
				</p>
				<p class="services-redirect"><a class="services-redirect" href="car-finder">KNOW MORE</a></p>
			</li>
		</ul>

		<ul class="ul-services-page2">	
			<li class="li-services-page2">
				<p class="service-icon"><img src="<?php echo $mediaUrl?>wysiwyg/Advertise_with_us-icon.png" /></p>
				<p class="lbl-service">Advertise With Us</p>
				<p class="service-desc">
					Over a million and more buyers from a small-to-medium auto-related enterprises all over the city rely online to discover, compare and purchase the products and services they need for their business. 
				</p>
				<p class="services-redirect"><a class="services-redirect" href="inquiry/index/advertise">KNOW MORE</a></p>
			</li>

			<li class="li-services-page3">
				<div class="services-buysell-page">
				<div class="services-buysell-page-img">
					<img src="<?php echo $mediaUrl?>wysiwyg/We_Buy_Sell_your_cars-icon.png" />
				</div>
				<div class="services-buysell-page-desc">
					<p class="buysell-lbl-page">Buy/Sell Your Car</p>
					<p class="buysell-desc-page">
						Autosupply provides a wide variety of updated listings and make it as your ultimate guide to buy or sell your cars here on our platform
					</p>
					<a class="services-redirect" href="buy-sell-your-car">KNOW MORE</a>
				</div>
	</div>
			</li>
		</ul>
	</div>
</div>

<style>
.header-bottom {
    border-bottom: 1px solid #ed1f24;
    border-bottom-width: medium;
    margin: 0 auto;
    width: 5%;
}

.header-srvc-page p {
    text-align: center;
    font-size: 24px;
    font-weight: bold;
    padding: 40px 0;
}

.ul-services-page{
    list-style: none;
    display: inline-flex;
    padding: 20px 0 0 0;
    margin: 20px 0 0 0;
}

li.li-services-page {
    width: 50%;
    padding: 0px 0px 50px 0px;
    margin: 0px 0px 0px 30px;
}

p.services-redirect {
    text-align: center;
    margin-top: 30px;
}

a.services-redirect{
    font-size: 12px;
    background: none;
    color: #ed1f24;
    border: 2px solid #ed1f24;
    border-radius: 30px;
    padding: 7px 30px;
    text-transform: uppercase;
    margin: 0;
}

a.services-redirect:hover{
    background-color: #ed1f24; 
    color: #fff;
}

.services-buysell-page {
    background: #f7f7f7;
    display: inline-flex;
    padding: 40px 0px 40px 20px;
    width: 100%;
}

.services-buysell-page-img {
    width: 45%;
}

.services-buysell-page-desc {
   	width: 55%;
}

.buysell-lbl-page {
    font-size: 28px;
    font-weight: 700;
}

.buysell-desc-page {
    font-size: 16px;
    padding: 10px 0 50px 0;
    width: 75%;
}

p.service-desc {
    text-align: left;
    min-height: 154px;
}


.ul-services-page2 {
    list-style: none;
    display: inline-flex;
    padding: 20px 0 0 0;
    margin: 20px 0 0 0;
}

li.li-services-page2 {
    width: 30%;
    padding: 0px 0px 50px 0px;
    margin: 0px 0px 0px 30px;
}

li.li-services-page3 {
    width: 60%;
    padding: 0px 0px 50px 0px;
    margin: 0px 0px 0px 30px;
}


.services-buysell-page-img img{
    width: 70%;
    margin-left: 15px;
}
</style>