<div class="shopslink">
	<div class="shopautoparts">
		<p class="shoplink-title">SHOP AUTO PARTS</p>
		<p class="shoplink-desc parts">Tires, tools, spares parts, batteries - we've got everything.</p>
		<p class="shoplink-now parts"><a href="parts.html">SHOP NOW</a></p>
	</div>
	<div class="shopcars">
		<p class="shoplink-title">SHOP CARS</p>
		<p class="shoplink-desc cars">The best brands all under one portal.</p>
		<p class="shoplink-now cars"><a href="cars.html">SHOP NOW</a></p>
	</div>
</div>
</div>