<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

<div class="header-support"><p>OPEN A TICKET</p>
<div class="header-bottom">&nbsp;</div>
</div>

<div class="div-support-intro">
<p class="div-support-intro-1">You'll get access to our support system by recording the incident that happened to you in a single transaction with us. Simply fil-out the information needed and we will make sure to attend to your concern as soon as possible. It is very important for us to know and record these incidents so we can continuously improve the services that we offer to our customers.<br/>

</p>
<p class="div-support-intro-1">
Our highly-trained staff assures the rectification of any untoward incidents that may happen upon fulfillment of any order that you made with us. <br/>
</p>

</div>

<div class="line"></div>
<div class="ticketstatus">
<label id="ticketstatus-lbl">Already opened a ticket?</label> <a class="support-redirect" href="insurance">CHECK TICKET STATUS</a>
</div>
<div class="line"></div>
<div class="dv-support">


<div class="header-support-form"><p>CONTACT INFORMATION</p>
</div>

<form class="form inquiry car form-inquiry-car"

action="<?php echo $block->getFormAction() ?>"

method="post"

id="inquirycar-form"

data-mage-init='{"validation":{}}'>

    <fieldset class="fieldset inquiry car">


        <div class="field field-email required">

            <label class="label" for="email">

                <span>Email Address</span>

            </label>



            <div class="control">

                <input type="text" id="email" name="email" value="" title="Email Address" class="input-text required-entry"  data-validate="{required:true, 'validate-email':true}">

            </div>

        </div>

        <div class="field field-fullname required">

            <label class="label" for="fullname">

                <span>Full Name</span>

            </label>



            <div class="control">

                <input type="text" id="fullname" name="fullname" value="" title="Full Name" class="input-text required-entry"  data-validate="{required:true}">

            </div>

        </div>


        <div class="field field-mobile required">

            <label class="label" for="mobile">

                <span>Contact Number</span>

            </label>



            <div class="control">

                <input type="text" id="mobile" name="mobile" value="" title="Contact Number" class="input-text required-entry"  data-validate="{required:true}">

            </div>

        </div>


        <div class="field field-company required">

            <label class="label" for="company">

                <span>Company</span>

            </label>

            <div class="control">

                <input type="text" id="company" name="company" value="" title="Company" class="input-text required-entry"  data-validate="{required:true}">

            </div>

        </div>

    </fieldset>



    <div class="actions-toolbar">

        <div class="primary">

            <button type="submit" class="action submit primary" title="Send"><span>Send</span></button>

        </div>

    </div>

</form>
    
</div>

<style>

.header-support p {
    text-align: center;
    font-size: 24px;
    font-weight: bold;
}

.header-support-form{
            padding: 30px;
}
.header-support-form p {
    text-align: center;
    font-size: 24px;
    font-weight: bold;
        color: #ed1f24;
}
.header-bottom {
    border-bottom: 1px solid #ed1f24;
    border-bottom-width: medium;
    margin: 0 auto;
    width: 5%;
}

/*.dv-support{
    display: none;
}*/

.div-support-intro {
    font-size: 14px;
    font-weight: 600;
    padding: 40px 0;
    width: 100%;
    margin: 0 auto;
}

p.div-support-intro-1{
    margin-top: 10px;
}

p.div-support-intro-2{
    margin-top: 50px;
}

.cms-support-with-us .column.main{
    width: 100%;
}


.cms-support-with-us .form.inquiry.car{
    width: 30%;
    min-width: 460px;
    margin: 0 auto;
}


a.support-redirect, button.action.submit.primary {
    font-size: 12px;
    background: none;
    color: #ed1f24;
    border: 2px solid #ed1f24;
    border-radius: 30px;
    padding: 7px 30px;
    text-transform: uppercase;
    margin: 0;
}

a.support-redirect:hover, button.action.submit.primary:hover {
    background-color: #ed1f24;
    color: #fff;
}


.line{
        border: 1px solid rgba(218, 217, 218, .87)!important;
}

.ticketstatus{
    width: 100%;
    text-align: center;
    padding: 20px;

}
#ticketstatus-lbl{
    font-weight: 600;
    font-size: 14px;
        margin-right: 30px;
}
</style>

