<div class="header-bottom">&nbsp;</div>
<div data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
    <div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
            <span>How do I purchase items in this website?</span>
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
           <b>Purchase Process<b><br>
			Autosupply.ph has a step-by-step process when a customer makes a purchase through our website.
			<br><br>
			
			<table>
				<tr>
					<td rowspan="2" width="10%">Step 1</td>
					<td>The customer logs in with his/her username and password.
					If the customer does not have an account yet, he/she is going to be prompted to create an account. (The purpose of this is to assure the legitimate existence of the customer)
					</td>
				</tr>
				
				<tr>
					<td>
						- Fill-out the information boxes.<br>
						- After filling out the boxes, click “Register”.<br>
						- The customer will then be prompted that he/she has already created his or her own account.
					</td>
				</tr>
				
				<tr>
					<td rowspan="2" width="10%">Step 2</td>
					<td>Once the customer has logged in. He/She can already navigate through the site by searching and browsing the products that he/she wishes to order.
					</td>
				</tr>
				
				<tr>
					<td>
						- The customer can also find and locate the items that he/she is looking for by simply typing it in the “search box”<br>
						- The customer can make comparisons from the specifications to the costs and savings of the items that he/she will choose.
					</td>
				</tr>
				
				<tr>
					<td rowspan="2" width="10%">Step 3</td>
					<td>The customer clicks the product/item that he/she wishes to order and places it in the cart.
					</td>
				</tr>
				
				<tr>
					<td>
						- The customer can randomly check the item, price, quantity and the total price of the products/items that he/she has ordered.
					</td>
				</tr>
				
				<tr>
					<td width="10%">Step 4</td>
					<td>The customer checks out the items in his or her cart.<br>
						The customer can review and finalize his/her order with its’ product name, price and quantity.
					</td>
				</tr>
				
				<tr>
					<td rowspan="2" width="10%">Step 5</td>
					<td>Once the order has been completed and registered by the customer. Autosuply.ph takes the process from here. Our staff in charge will prepare the purchase order(P.O.) to be sent to the supplier. The customer can also perform online payment if he/she wishes to do it. The purchase order is filled with these details:
					</td>
				</tr>
				
				<tr>
					<td>
						- Date <br>
						- P.O. Number <br>
						- Name of Supplier <br>
						- Quantity of the items ordered <br>
						- Item Specification <br>
						- Unit Price <br>
						- Total <br>
						- Item Picture (optional)

					</td>
				</tr>
				
				<tr>
					<td rowspan="2" width="10%">Step 6</td>
					<td>The Purchase Order (P.O.) is going to be sent to the staff in our warehouse.</td>
				</tr>
				
				<tr>
					<td>
						- The Purchase Order is undersigned by the person in-charge from Autosupply.ph before going to the warehouse. <br> 
						- The Purchase Order is sent through email, fax or delivered personally.  <br>
						- The warehouse will then send a confirmation reply upon receiving the Purchase Order.

					</td>
				</tr>
				
				<tr>
					<td rowspan="2" width="10%">Step 7</td>
					<td>Once the warehouse receives and confirms the Purchase Order.</td>
				</tr>
				
				<tr>
					<td>
						- They will then check the product. <br>
						- If the warehouse affirms that, the item is out of stock. <br>
						- The customer will be notified immediately by Autosupply.ph that the item is unavailable at the moment. <br><br>
						- Autosupply.ph will then give an option to whether the customer can wait for a short period of time (within the day) so they can locate right away a supplier with the item, available.<br>
						- If the customer says he/she can wait until the item is located, the purchase process continues.<br>
						- If the customer says he/she can’t wait, then the order will be cancelled.<br>
						- If the warehouse affirms that the item is available, the purchase process will continue.
					</td>
				</tr>
				
				<tr>
					<td rowspan="2" width="10%">Step 8</td>
					<td>Once the warehouse affirms that the item is good and ready, an Autosupply.ph staff will pick up the product or the item ordered.</td>
				</tr>
				
				<tr>
					<td>
						- The item will be attached with its duplicate invoice from the warehouse.
					</td>
				</tr>
				
				<tr>
					<td width="10%">Step 9</td>
					<td>The item will then be packed for delivery.</td>
				</tr>
				
				<tr>
					<td rowspan="2" width="10%">Step 10</td>
					<td>The customer will be notified before the delivery to inform him/her about the ETA details.</td>
				</tr>
				
				<tr>
					<td>
						- While the item/order is on its way, the customer will be informed in several ways. <br>
						The customer can either be: <br>
						- Reached by a phone call through his/her mobile. <br>
						- Sent an e-mail. <br>
						- Sent a text message. <br>
					</td>
				</tr>
				
				<tr>
					<td rowspan="2" width="10%">Step 11</td>
					<td>Upon order delivery.</td>
				</tr>
				
				<tr>
					<td>
						The customer will either be: <br>
						- Sent a text message when the order has arrived. <br>
						- Reached by a phone call through his/her mobile when the order has arrived. <br>
						- The customer is given an original copy of the invoice/official receipt. <br>
						- The payment process will take place. Cash on Delivery (COD) <br>
					</td>
				</tr>
				
				<tr>
					<td width="10%">Step 12</td>
					<td>Orders Fulfilled. The customer can freely decide on whether he/she is going to make an online review, feedback, suggestions, and complaints thru: <br>
						- Autosupply.ph website <br>
						- Social media <br>
						- Our Help/Support centre <br>
						- Online Chat
					</td>
				</tr>
			</table>
        </p>
    </div>
	
    <div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           How much is the shipping Fee? 
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            Autosupply.ph offers free shipping on selected items within the metro.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           How to check my shipping Fee? 
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            During checkout process, you can check your shipping fee in the Order Summary box.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           Shipping Fee is for what?	
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
           Your shipping fee (and also bulky fee if any) is used to pay for licensing and insurance that protect you and your goods against unscrupulous or hazardous situations.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           Does Autosupply.ph charge additional fees for bulky items?	
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
           Here in Autosupply.ph we not only give you the lowest prices possible, we also want our valued customers to save as much as you can, which is why we no longer charge bulky fees to heavy items, such as, home appliances.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           How do I check delivery lead time of a product?	
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
           Click on the product you want and go to its product detail page. You will see the delivery lead time of that product on the right side of the page.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           Can I schedule the delivery of my order?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
           Our courier service is unable to provide scheduling of deliveries; therefore we can not guarantee delivery of your order for a specific time or date.
			Yet you can rest assured we are working closely with our service partners to allow us to better serve you in the future.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           How do I track my orders?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
			HOW TO TRACK ORDERS<br>
			Are you worried about your order? Track your orders easily and hassle-free. You can track your order any time of the day by simply following these easy steps.
			<br><br>
			
			<table>
				<tr>
					<td width="10%">Step 1</td>
					<td>Go to Order Tracker’s page (www.autosupply.ph/ordertracker)
					</td>
				</tr>
				
				<tr>
					<td width="10%">Step 2</td>
					<td>Fill out the data needed.<br>
						- Order Number <br>
						- Email Address
					</td>
				</tr>
				
				<tr>
					<td rowspan="2" width="10%">Step 3</td>
					<td>Click the “Track” button 
					</td>
				</tr>
				
				<tr>
					<td>
						Once you clicked the button the information you need will appear on your screen to get you updated about the status of your order.
						Our system is always updated every single day to impart you the freshest and the latest information you need to know about your order.
					</td>
				</tr>
			</table>
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           I don’t see any information about the status of my order on this page. How do I get the info I need?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            In the event that the you cannot see any information about your order, please do not hesitate to reach us on our social media pages. <br/>
			Message us @ our: <br/>
			Facebook page: https://www.facebook.com/pg/Autosupplyph-1280463662035306/about/ <br/>
			Instagram: https://www.instagram.com/autosupplysocial/ <br/>
			Twitter: https://twitter.com/autosupplyph <br/><br/>

			Or call us @ Tel no. 3729146 (office hours)
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           When is the arrival of my delivery?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            Right after, officially placing your order, our system will conduct a confirmation process and inform you about it through your email or mobile number. The confirmation process will take about 24 to 48 hours after the order has been placed.
			The arrival of your order will take place within seven days. The items you ordered can be delivered on the next working day, the soonest, and on the seventh working day, the latest. (Holidays don’t count as working days) – Metro Manila. 
			In other places specially the non-Metro Manila areas, the delivery will take place from 7 to 15 working days. However, there is also a good chance that if the item is available and in stock, the soonest possible time of the delivery can be also be within seven working days.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           I ordered several items but the courier only delivered one, where are the other items?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            Whenever we encounter multiple items in a single order, we ship each item as soon as they are made available. Shipping time for all items under one order number will still follow the applicable delivery time frame in your area. 
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           Can I make some prearrangements on the date of my delivery?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            Yes, it’s possible, but please be advised that we cannot guarantee the delivery of the item on the exact date as you prefer. We can only move the date time frame of the delivery in line with the date you wish to prearrange.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           Is it possible for you to deliver on weekends?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            It will always depend on the availability of our partner couriers. It is possible but there is no assurance, however, the chance is always bigger. You will be notified on the day of your delivery.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           Is there such things such expedite delivery?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            The delivery is always within the time frame. We will follow the schedule as it is handled by our partner couriers. 
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           How do I get the exact date of my delivery?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            Unfortunately, we are not able to give you the exact time and date of the delivery but you can always track the status of your items for you to monitor and estimate the date of arrival.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           Can I ship my items to my office or to another address?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            Yes, it’s possible provided that you will fill in the necessary information we need in the delivery address box. Anyway, you will be given notice thru text messaging or email about the confirmation of your order and the complete delivery address will also be posted.
        </p>
    </div>
	
	<div data-role="collapsible" class="faqs-title">
        <div data-role="trigger">
           Can I pick up my order at autosupply.ph office/warehouse?
        </div>
    </div>
    <div data-role="content" class="faqs-content">
        <p>
            Unfortunately, we do not offer this option as of now.
        </p>
    </div>		<div data-role="collapsible" class="faqs-title">        <div data-role="trigger">           I have an inquiry about a spare part(s) that I need for my car and it’s a bit difficult to find it, can autosupply.ph help me?        </div>    </div>    <div data-role="content" class="faqs-content">        <p>            Autosupply.ph can definitely give you a hand. We have set a section on our website where you can fill up a form and submit that for us to locate the spare part(s) that you are looking for. We’ll give you a direct response within the day.			<br/><br/>			When you decide to order a spare part(s) that we’re going find and locate for you, we will be requiring a 50% down payment to secure the process of the order. You can still pay through COD (Metro Manila Only) once we have delivered you the item that you ordered or you can also pay through other means of payment available here on our website.        </p>    </div>
	
	
	
</div>