<div class="header-bottom">&nbsp;</div>
<div class="terms-content">
	<p>
		Your overall utilization and access of the services that we offer are all subject to the Terms of Use of this platform. By your access and response to aid your demands and needs through this site, you agree and acknowledge to be bound under these Terms of Use.  If by any means, you are in dispute nor opposed to these terms, do not use or access the platform. 
		Gaining access to areas in this platform that are restricted by passwords are only allowed to customers/clients with active accounts at Autosupply.ph. Unauthorized attempt to gain entry in such parts of this platform or to any other confidential information is strictly prohibited. <br/><br/>
		If by any chance you are 18 years old, we will require you to have a consent from your parents or legal guardian. Their acceptance of these Terms of Use means they agree to be held liable for any actions or any charges associated with your use of any services or purchase of products that are offered in these platform. In the event that you fail to have any consent from them, discontinue your use and access of this Platform at all cost. <br/><br/>
		If you have any questions about these terms, please send any inquiry to us via e-mail to: <br/>
		We encourage you to print a copy or save a local copy of these Terms for your records.<br/><br/><br/>
	</p>
	
	<p class="terms-title"> 1.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;The Overall use of the Services and access to our site. </p> <br/><br/>
	<p>Guidelines to the use of this Platform or Services: You agree to abide by and comply with all the guidelines, notices, operational rules, policies and instructions pertaining to the use of the Services and access of this Platform. We reserve the rights to make changes or revisions to these guidelines any time and with full understanding, you agree to take the responsibility of being updated to any changes that might occur upon their publication on the Platform.</p> <br/><br/>
	
	<table>
		<tr>
			<td>1.1</td>
			<td>The following are the activities that you are not allowed to do when you are using the Platform. You are not allowed to: <br>
				<ul>
					<li>Use the platform and its services for any illegal purposes.</li>
					<li>Duplicate an entity or misquote your affiliation with any person illegally.</li>
					<li>Hinder others to enjoy their use of the platform.</li>
					<li>Post or advertise through the Platform any material that is prohibited by the law.</li>
					<li>Attempt to gain unauthorized entry to damage any other computer systems or networks attached to our platform or services. </li>
					<li>Transmit any software that contains viruses or any damaging component which may corrupt the platform’s data and will eventually result to having major technical problems on the operation of the customer’s computer or mobile or the site itself.</li>
					<li>Use the platform other than in conformance with the acceptable use policies of any connected computer networks, any applicable Internet standards and any other applicable law.</li>
				</ul>
			</td>
		</tr>
		
		<tr>
			<td>1.2</td>
			<td>The Platform’s Availability: At times and without releasing any prior notice, we may suspend or discontinue the provision of the platform and the services that it offers and shall not be held liable if any upgrade hinders or prevents you from gaining entry to the platform and the services it offers.
			</td>
		</tr>
		
		<tr>			
			<td>1.3</td>
			<td>Our right in this Platform: It is our right but not our obligation to monitor or control any activity or content on our platform and for that, we encourage you to understand the following: <br/><br/>
				In this platform, we own the right to:<br/><br/>
				 
				<ul>
					<li>Investigate, on our own disposition, any violations of the terms and conditions posted herein and implement appropriate sanctions in accordance to its level and gravity.</li>
					<li>Restrict access of any customer to the platform whose intention is to damage any content or interfere with the platform’s overall operations.</li>
					<li>Report any activity that is suspected to be in violation of any applicable law in observance of our cooperation with any investigation conducted by the appropriate authorities. </li>
					<li>Ask any information from you with regards to your use of the platform and services that we offer any time. Refusal to disclose any data needed would mean opposition that leads to the coverage of our privacy policy protecting other customers and the business itself.</li>
				</ul>
			</td>
		</tr>
		
		<tr>
			<td>1.4</td>
			<td>Privacy Policy: Your access and use of this platform is subject to our Privacy Policy as set out here.
			</td>
		</tr>
		
		<tr>
			<td>1.5</td>
			<td>Added terms: In addition to these terms of use, more improved versions of contents offered by us are all subject to additional terms and conditions, which will apply in full effect.
			</td>
		</tr>
	</table>
	<br/><br/>
	
	<p class="terms-title"> 2.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;The use of our Services</p> <br/>
	
	<table>
		<tr>
			<td>2.1</td>
			<td>Restrictions under the use of the platform: Use of the services offered by us is limited to authorized customers, who are 18 years old and above, with the capacity to understand and abide by the policies and regulations herein. Customers who are in breach or who breached the terms and conditions of this platform will not be allowed to use the services even if they fulfill the requirements needed in relevance to their demand.
			</td>
		</tr>
		
		<tr>			
			<td>2.2</td>
			<td>Our General terms of use, you approve to:<br/><br/>
				<ul>
					<li>To make sure that any information you post or share related to your use the of the platform and its services is correct, transparent and accurate.</li>
					<li>To gain entry and use the platform and the services it offers only for legal purposes at all times.</li>
				</ul>
			</td>
		</tr>
		
		<tr>
			<td>2.3</td>
			<td>Our product information: We commit to provide correct and precise information/description about our products and services. However, we do not guarantee that all the data posted about the products and services we offer are all accurate and error free.
			</td>
		</tr>
		
		<tr>
			<td>2.4</td>
			<td>Tax: All products that we offer are subject to taxes. The prices that are posted on our site already has taxes on it. We reserved the right to make adjustments or changes on the listing prices at any time without any prior notice.
			</td>
		</tr>
	</table>
	
	<br/><br/>
	
	<p class="terms-title"> 3.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;Account holders of autosupply.ph</p> <br/>
	
	<table>
		<tr>
			<td>3.1</td>
			<td>Creating an Account: There are certain services that may require you to create an account with us. Thus, this allows you to have a faster transaction. You will be required to provide some personal information for our records and for your future transactions. Decide on whether what kind of username and password you desire to have. We may request you, at any given time, to update the information that you have initially provided. We may also remind you to always be conscious in safeguarding your information because we will not be held liable for any loss or breach in any level. You hereby agree to change your Password from time to time and to keep the Username and Password confidential and shall be responsible for the security of your account and liable for any disclosure or use (whether such use is authorized or not) of the Username and/or Password. Do not hesitate to inform us immediately if you believe that the confidentiality of your own personal information has been violated.
			</td>
		</tr>
		
		<tr>			
			<td>3.2</td>
			<td>Breached Account: Any use or access to the platform using your username and password will be accounted to you. All transactions carried out by your account is your full responsibility. You further agree and acknowledge that you shall be bound by and agree to fully indemnify us against all losses attributable to any use of any Services and/or or access to the Platform referable to your Username and Password.
			</td>
		</tr>
	</table>
	<br/><br/>
	
	<p class="terms-title"> 4.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;Intellectual Property Ownership</p> <br/>
	
	<table>
		<tr>
			<td>4.1</td>
			<td>Ownership: Autosupply.ph owns all intellectual property in this platform. It is licensed and controlled by us (autosupply.ph) and our service providers. We reserve the right of the copyright policies under the constitution to fully enforce its implementation.
			</td>
		</tr>
		
		<tr>			
			<td>4.2</td>
			<td>Restriction: At any given time, there shall be no part or material in this platform that may be reproduced, modified, displayed nor framed in any manner unless a written permission is presented undersigned by its copyright owners. <br/><br/>
				A permit may only be given to requesters for non-commercial purposes and shall be asked to present a full document of the finished report to reassure that the purpose was fulfilled.
			</td>
		</tr>
	</table>
	<br/><br/>
	
	<p class="terms-title"> 5.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;Our Limitations</p> <br/>
	
	<table>
		<tr>
			<td>5.1</td>
			<td>Representations: Every single piece of information in the Platform are posted for informational purposes only. We do not warrant the accuracy and adequacy of all the data posted in the platform. Same goes with the totality of the platform being free from all kinds of errors, computer viruses, malicious and destructive codes and programs. All slipups shall be rectified as soon as it has been identified by our officers. The security of any information transmitted by you through the use of the platform shall also be not warranted by autosupply.ph.
			</td>
		</tr>
		
		<tr>			
			<td>5.2</td>
			<td>Liability exclusions: autosupply.ph shall not be liable for any loss caused by: (1) any system or   connection failure, interruption, delays, viruses and other programs that may affect the whole performance of the platform.
			</td>
		</tr>
		
		<tr>			
			<td>5.3</td>
			<td>Customer’s Interpretation: Any form of misinterpretation resulting to misuse of the Platform is entirely at your own risk and we shall not be held liable for any damage(s) that might cause you.
			</td>
		</tr>
	</table>
	<br/><br/>
	
	<p class="terms-title"> 6.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;Updates and Promotions</p> <br/>
	
	<table>
		<tr>
			<td>6.1</td>
			<td>Updates: Alerts for updates are continuously done at any given time, the account holders will automatically be informed as it is one of our primary tasks and it is upon the discretion of autosupply.ph to whether an account holder may be subjected for notification if found linked in any kind of issue. Updates: Alerts for updates are continuously done at any given time, the account holders will automatically be informed as it is one of our primary tasks and it is upon the discretion of autosupply.ph to whether an account holder may be subjected for notification if found linked in any kind of issue. 
			</td>
		</tr>
		
		<tr>			
			<td>6.2</td>
			<td>Promotions: We may attach banners to the platform for the purposes of promoting our Third-party vendor’s products and services. To nullify doubts, you shall not receive any payments, fees or commission in respect of any such promotional material.
			</td>
		</tr>
	</table>
	<br/><br/>
	
	<p class="terms-title"> 7.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;Submission of information</p> <br/>
	
	<table>
		<tr>
			<td>7.1</td>
			<td>Your submissions: You are licensing us to use the materials or information that you submit to the Platform and/or provide to us, including but not limited to, questions, reviews, comments, and suggestions. When you post comments or reviews to the Platform, you also grant us the right to use the name that you submit or your Username in connection with such review, comment, or other content. You are not allowed to use a false e-mail address, pretend to be someone other than yourself or otherwise mislead us to the source of any submissions. We may, but shall not be obligated to, publish, remove or edit your entries (submissions).
			</td>
		</tr>
		
		<tr>			
			<td>7.2</td>
			<td>Your approval for us to send e-mails: You are giving us an authority to process any information provided by you for the purposes of sending informational and promotional e-mails and notices, updates and other information to you. Your agreement to this provision constitutes your consent for the purpose of the provisions of any spam control laws (whether in Philippines or elsewhere). However you can choose not to receive any promotional e-mails by clicking on the appropriate hyperlink in any promotional e-mail.
			</td>
		</tr>
	</table>
	<br/><br/>
	
	<p class="terms-title"> 8.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;Termination</p> <br/>
	
	<table>
		<tr>
			<td>8.1</td>
			<td>Our termination: Your use of Username and Password will depend on us whether to terminate it or not under certain circumstances affecting the website and operations negatively. We may not let you access the Platform and/or Services (or any part thereof) for the negative reasons whatsoever, including a breach of any of these Terms of Use or where if we believe that you have violated or acted inconsistently with any terms or conditions set out herein, it is not suitable to continue providing the services relating to the Platform.
			</td>
		</tr>
		
		<tr>			
			<td>8.2</td>
			<td>Your termination: You may terminate these Terms and conditions by giving notice in writing to us.
			</td>
		</tr>
	</table>
	<br/><br/>
	
	<p class="terms-title"> 9.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;Notices</p> <br/>
	
	<table>
		<tr>
			<td>9.1</td>
			<td>Notices form autosupply.ph: All notices are given to you through:<br><br>
				<ul>
					<li>verbal encounter and recorded by authorized staff or electronic media as we it is given on the day of publication or broadcast, or</li>
					<li>sent by post to be received by you on the day or day(s) after it was broadcasted.</li>
				</ul>
			</td>
		</tr>
		
		<tr>			
			<td>9.2</td>
			<td>Notices coming from you: You are only allowed to give notices to us in writing sent to our designated address or e-mail address. We will do our best to respond promptly but there is no guarantee to reply with consistent speed.
			</td>
		</tr>
	</table>
	
	<div class="page-title-wrapper">
		<h1 class="page-title">
			Changes to the Privacy Policy    
		</h1>
    </div>
	<div class="header-bottom">&nbsp;</div>
	
	<p>Autosupply.ph systematically evaluates the contents of this Terms of Use to make changes and revisions for the improvement and development of the procedures protecting the interest of all parties involve. We reserve the right to amend the Terms of Use at any given period of time and without any prior notice. <br/><br/>
		Changes will be posted on the website indicating the exact details of when it was last updated.
	</p>
</div>