<div class="header-bottom">&nbsp;</div>
<div class="payments-content">
	<p>
		
		The warranty of our products will vary depending on its brands, from the time it was purchased. This information will be posted along with the other specifications. Take note of each item’s warranty for it will also be the basis of your choice whether you would prefer to purchase it or not.  <br/><br/>
		The return/refund request process is done via Autosupply.ph website, our landlines or chat support. The customer should provide all the information needed on the return request form to speed up the return. This includes the customer’s name, contact number, pick-up location, tracking number, SKU and the quantity of the item(s) returned. The customer is free to decide whether the return will be a replacement or a refund. <br/><br/>
		The reason for the return/refund is going to be validated and the reasons that we accept are damaged item, defective item, wrong item delivered, missing parts and order not received. Our highly-trained representatives will pick-up the returned item(s) at the pick-up locations set by the customer. <br/><br/>
		The customer will be notified about their return/refund status every now and then. The notification will be either thru a phone call, an e-mail or thru a text message. <br/><br/>
		The whole refunding process takes 15-30 days. The refund can either be thru bank deposit or thru our courier partners.

	</p>
</div>