<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
		<strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Why should you register?')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
		<?= $block->escapeHtml(__('Here at Autosupply.ph we prioritize your convenience, so we encourage you to register for us to personalize your own shopping experience, suggest items according to your preference, enjoy faster transactions, have quicker payment process, easily track your orders and many more.')) ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
