<?php


    $showsuccessmessage = 0;
    // $ifsuccess = $_GET['success'];

    // if($ifsuccess == true){
    //     $showsuccessmessage = 1;
    // }


$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<div class="header-support">
<div class="header-bottom">&nbsp;</div>
</div>

<div class="div-support-intro">
<p class="div-support-intro-1">Please insert your ticket number to check the status of your concern.<br/>
    <span style="font-family: 'Muli ExtraBold';">Don't know your ticket number?</span> Our team sends your ticket number via email.
</p>


</div>

<form class="form inquiry car form-inquiry-car"

action="<?php echo $block->getFormAction() ?>"

method="post"

id="inquirycar-form"

data-mage-init='{"validation":{}}'>

    <fieldset class="fieldset inquiry car">

        <div class="field field-fullname required">

            <label class="label" for="fullname">

                <span>Full Name</span>

            </label>



            <div class="control">

                <input type="text" id="fullname" name="fullname" value="" title="Full Name" class="input-text required-entry"  data-validate="{required:true}">

            </div>

        </div>


        <div class="field field-ticketnumber required">

            <label class="label" for="ticketnumber">

                <span>Ticket Number</span>

            </label>



            <div class="control">

                <input type="text" id="ticketnumber" name="ticketnumber" value="" title="Ticket Number" class="input-text required-entry"  data-validate="{required:true}">

            </div>

        </div>

            <center>
            
                <?php echo $this->getLayout()->createBlock("Monashee\Recaptcha\Block\Recaptcha")->setTemplate("Monashee_Recaptcha::recaptcha.phtml")->toHtml();?>
            
            </center>

    </fieldset>



    <div class="actions-toolbar">

        <div class="primary">

            <button type="submit" class="action submit primary" title="Send"><span>Send</span></button>

        </div>

    </div>

</form>
    
</div>

<style>

.header-support p {
    text-align: center;
    font-size: 24px;
    font-weight: bold;
}

.header-support-form{
            padding: 30px;
}
.header-support-form p {
    text-align: center;
    font-size: 24px;
    font-weight: bold;
        color: #ed1f24;
}
.header-bottom {
    border-bottom: 1px solid #ed1f24;
    border-bottom-width: medium;
    margin: 0 auto;
    width: 5%;
}

/*.dv-support{
    display: none;
}*/

.div-support-intro {
    font-size: 14px;
    font-weight: 600;
    padding: 40px 0;
    width: 100%;
    margin: 0 auto;
}

p.div-support-intro-1{
    margin-top: 10px;
    text-align: center;
}

p.div-support-intro-2{
    margin-top: 50px;
}

.cms-support-with-us .column.main{
    width: 100%;
}


.cms-support-with-us .form.inquiry.car{
    width: 30%;
    min-width: 460px;
    margin: 0 auto;
}


a.support-redirect, button.action.submit.primary {
    font-size: 12px;
    background: none;
    color: #ed1f24;
    border: 2px solid #ed1f24;
    border-radius: 30px;
    padding: 7px 30px;
    text-transform: uppercase;
    margin: 0;
}

a.support-redirect:hover, button.action.submit.primary:hover {
    background-color: #ed1f24;
    color: #fff;
}


.line{
        border: 1px solid rgba(218, 217, 218, .87)!important;
}

.ticketstatus{
    width: 100%;
    text-align: center;
    padding: 20px;

}
#ticketstatus-lbl{
    font-weight: 600;
    font-size: 14px;
        margin-right: 30px;
}

.form-inquiry-car {
    padding: 10px 0 70px 0;
}
.g-recaptcha {
/*    width: 22%;
    margin: 0 auto;
    position: relative;
    top: -170px;*/
}

.actions-toolbar{
    position: relative;
    top: 50px;
}

.form.inquiry.success{
    box-shadow: 0 0 20px 0 #888888;
    background: #fff;
    border-radius: 5px;
    width: 40%;
    min-width: 500px;
    margin: 0 auto;
}

.success-div{
    text-align: center;
    padding: 50px;
}
h3.success-title {
    color: #C81C1F;
}
p.success-icon {
    width: 20%;
    margin: 0 auto;
}

p.success-label {
    width: 75%;
    margin: 0px auto;
    font-family: 'Muli Bold';
    font-size: 16px;
    margin-top: 20px;
}
</style>