<?php
 $showsuccessmessage = 0;
    $serviceID = $_GET['id'];

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        if($serviceID == "success"){
        $showsuccessmessage = 1;
        $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
        $currentStore = $storeManager->getStore();
        $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
        $baseUrl = $currentStore->getBaseUrl();
    }else{
        $collection = $objectManager->get('\Magento\Cms\Model\ResourceModel\Page\CollectionFactory')->create();
// add Filter if you want 
    $collection->addFieldToFilter('is_active' , \Magento\Cms\Model\Page::STATUS_ENABLED)
                ->addFieldToFilter('page_id', array(
                'from' => 13,
                'to' => 20
                ));

    $pages = array('default' => '(Default) Customer Login Page');

    }

?>
<?php if($showsuccessmessage == 1){ ?>
<form class="form inquiry success form-inquiry-car">
    <fieldset class="fieldset inquiry car">
    <div class="success-div">
        <p class="success-icon"><img src="<?php echo $mediaUrl?>wysiwyg/Form_sent-icon.png" /></p>
        <h3 class="success-title">Thank you!</h3>
        <p class="success-label">Your message has been sent. Please expect our response shortly.</p>
    </div>
    </fieldset>
<style>
.g-recaptcha{
    display: none;
}
</style>
<?php }else{ ?>

<form class="form inquiry car form-inquiry-car"

action="<?php echo $block->getFormAction() ?>"

method="post"

id="inquirycar-form"

data-mage-init='{"validation":{}}'>

    <fieldset class="fieldset inquiry car">

        <div class="field field-fullname required">

            <label class="label" for="fullname">

                <span>Full Name</span>

            </label>



            <div class="control">

                <input type="text" id="fullname" name="fullname" value="" title="Full Name" class="input-text required-entry"  data-validate="{required:true}">

            </div>

        </div>



        <div class="field field-mobile required">

            <label class="label" for="mobile">

                <span>Contact Number</span>

            </label>



            <div class="control">

                <input type="text" id="mobile" name="mobile" value="" title="Contact Number" class="input-text required-entry"  data-validate="{required:true}">

            </div>

        </div>



        <div class="field field-email required">

            <label class="label" for="email">

                <span>Email Address</span>

            </label>



            <div class="control">

                <input type="text" id="email" name="email" value="" title="Email Address" class="input-text required-entry"  data-validate="{required:true, 'validate-email':true}">

            </div>

        </div>


        <div class="field field-service required">

            <label class="label" for="email">

                <span>Service</span>

            </label>



            <div class="control">
                <select class="validate-select" title="services" id="services" name="services" data-validate="{required:true, 'validate-select':true}">>
                <option value="" 
                    <?php echo "selected='selected'";?> style="display:none;">
                    -- Please Select --
                </option>
                <option value="insurance" 
                    <?php if($serviceID == 1): echo "selected='selected'"; endif;?>>
                    Insurance
                </option>
                <option value="car maintenance" 
                    <?php if($serviceID == 2): echo "selected='selected'"; endif;?>>
                    Car Maintenance
                </option>                
                <option value="parts installation" 
                    <?php if($serviceID == 3): echo "selected='selected'"; endif;?>>
                    Parts Installation
                </option>
                <option value="car care and Detailing" 
                    <?php if($serviceID == 4): echo "selected='selected'"; endif;?>>
                    Car Care & Detailing
                </option>
                <option value="parts finder" 
                    <?php if($serviceID == 5): echo "selected='selected'"; endif;?>>
                    Parts Finder
                </option>
                <option value="car finder" 
                    <?php if($serviceID == 6): echo "selected='selected'"; endif;?>>
                    Car Finder
                </option>
                <option value="buy sell your car" 
                    <?php if($serviceID == 7): echo "selected='selected'"; endif;?>>
                    Buy / Sell your car
                </option>

                </select>
            </div>

        </div>


        <div class="field field-inquiry required">

            <label class="label" for="inquiry">

                <span>Inquiry</span>

            </label>



            <div class="control">

                <textarea id="inquiry" name="inquiry" value="" title="Inquiry" class="input-text required-entry"  data-validate="{required:true}" rows="7"></textarea>

            </div>

        </div>

    </fieldset>




    <div class="actions-toolbar">

        <div class="primary">

            <button type="submit" class="action submit primary" title="Send"><span>Send</span></button>

        </div>

    </div>

    <?= $block->getChildHtml('form_additional_info') ?>
        <?php } ?>
</form>

<style>

.form-inquiry-car {
    padding: 10px 0 70px 0;
}
.g-recaptcha {
    width: 30%;
    margin: 0 auto;
    position: relative;
    top: -140px;
}

.actions-toolbar{
    position: relative;
    top: 50px;
}

.form.inquiry.success{
    box-shadow: 0 0 20px 0 #888888;
    background: #fff;
    border-radius: 5px;
    width: 40%;
    min-width: 500px;
    margin: 0 auto;
}

.success-div{
    text-align: center;
    padding: 50px;
}
h3.success-title {
    color: #C81C1F;
}
p.success-icon {
    width: 20%;
    margin: 0 auto;
}

p.success-label {
    width: 75%;
    margin: 0px auto;
    font-family: 'Muli Bold';
    font-size: 16px;
    margin-top: 20px;
}
</style>