<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category

	/* Insert Rentals Description */
	$category           = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
	$currentcategory    = $category->getName(); //Current Category Name

	if($currentcategory == "Rentals and Leasing"){
	?>
		<div class="div-careers-intro">
		<p class="div-careers-intro-1">We also offer car rentals and leasing that assures the overall safety and security of the clients. Exceptional and well-trained personnel cheerfully look after the day to day issues, and provide the needs of our clients, renters and customers.
		</p>
		</div>
	<?php
	}
	/* Insert Rentals Description */
?>



<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?= /* @escapeNotVerified */ __('Shop By') ?></strong>
        </div>

        <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= /* @escapeNotVerified */ $block->getClearUrl() ?>" class="action clear filter-clear"><span><?= /* @escapeNotVerified */ __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
				<?php if ($filter->getItemsCount()): ?>
					<?php if (!$wrapOptions): ?>
						<?php $collapsibleRange = implode(' ', range(0, $filter->getItemsCount())); ?>
						<strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php echo $category->getName() . ' Finder';?></strong>
						<div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": "<?php echo $collapsibleRange ?>", "multipleCollapsible": true}}'>
					<?php  $wrapOptions = true; endif; ?>
					<div data-role="collapsible" class="filter-options-item">
					<div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
					<div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
				</div>
				<?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
