<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
	
	$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
	$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
	$currentStore = $storeManager->getStore();
	$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
        <!--<div class="post-header clearfix">
            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
            <?php //echo $this->getInfoHtml() ?>
        </div>-->

        <div class="post-content">
            <div class="post-description clearfix">
                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                <div class="post-ftimg-hld">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </div>
                <?php } ?>
                <div class="post-text-hld">
                    <?php echo $block->getContent() ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
		
		<div class="post-social">
			<ul>
				<li class="lbl-social">Share this on: </li>
				<li><img src="<?php echo $mediaUrl?>wysiwyg/Facebook-icon.png" /></li>
				<li><img src="<?php echo $mediaUrl?>wysiwyg/Twitter-icon.png" /></li>
			</ul>
		</div>

        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>