<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$serviceid = 7;

?>

<div class="header-bottom">&nbsp;</div>
</div>

<div class="cms-main-container">
	<div class="cms-container buysell">
		<div class="cms-image-container">
			<img src="<?php echo $mediaUrl?>wysiwyg/Buy_Sell_Your_Car-image.png" />
		</div>
		<div class="cms-desc-container">
			<p class="cms-desc">
				Autosupply.ph provides a wide variety of updated listings and make it as your ultimate guide to buy or sell your cars here on our platform. We aim to provide quality service and assistance to you, our customers, who are looking for your first or replacement car, with great value for money, we can lead you to get the best car according your preferences. 
			</p>
		</div>
	</div>
</div>

<div class="div-services-inquire">
	<div class="header-services-inquire">Interested?</div>
	<p class="inquire-desc">Dont hesitate to contact us. Send an inquiry now and we'll get back to you shortly.</p>
	<p class="services-inquire">
		<a class="action inquirenow" href="/inquiry/index/services?id=<?php echo $serviceid; ?>">INQUIRE NOW</a>
	</p>
</div>